config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  get '/info', to: 'static_pages#info'
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/impersonation-book/sitemaps/sitemap.xml.gz")
  get 'search_tag', to: 'targets#search_tag'

  resources :users, only: %i[new create show edit update]

  resources :targets do
    resources :results, only: %i[create]
  end

  resources :results, only: %i[index show edit update destroy] do
    resources :collaborations, only: %i[new create]
    resources :comments, only: %i[create destroy]
  end

  resources :collaborations, only: %i[destroy update show edit index] do
    resources :collaboration_comments, only: %i[create destroy]
  end
  
  resources :votes, only: %i[new create destroy index] do
    resource :likes, only: %i[create destroy]
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'ranks', to: 'ranks#index'
  get 'boards', to: 'boards#index'
  get 'collaboration_boards', to: 'collaboration_boards#index'

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy]
    resources :targets, only: %i[create new index edit update show destroy]
    resources :tags, only: %i[create new index edit update destroy]
    resources :results, only: %i[index]
    resources :collaborations, only: %i[index]
  end

end

app/controllers/collaboration_boards_controller.rb
class CollaborationBoardsController < ApplicationController
    def index
        @collaboration_boards = Collaboration.where(state: "published").includes(:user, :result).order(created_at: :desc)
    end
end

app/views/collaboration_boards/_collaboration_board.html.erb
<% user = User.find(collaboration_board.user_id) %>
<% result = Result.find(collaboration_board.result_id) %>
<div class="card shadow mr-3 mx-auto" style="width: 25rem;">
    <div class="card-body">
      <h5 class="card-title"><%= collaboration_board.title %></h5>
      <p class="card-text">by <%= user.name %></p>
      <%=audio_tag("#{collaboration_board.collaboration_voice.url}", controls: true) %>
      <p class="card-text"><%= collaboration_board.body %></p>
       <%= link_to "もっと見る", collaboration_path(collaboration_board), class: 'btn btn-info float-right' %>
    </div>
</div>

app/views/collaboration_boards/index.html.erb
<% set_meta_tags title: t('.title') %>
<div class="container-fluid mt-5">
  <h1 class="text-center text-muted"><i class="fa-solid fa-people-carry-box mr-2"></i><%= t('.title') %></h1>
  <div class="collaboration-boards-wrapper text-muted">
    <div class="top-collaboration-boards pt-5 pb-4">

      <!-- カード一覧 -->
        <div class="row">
          <% if @collaboration_boards.present? %>
            <%= render partial: 'collaboration_board', collection: @collaboration_boards %>
          <% else %>
            <p>公開されているコラボはありません。</p>
          <% end %>
        </div>
    </div>
  </div>
</div>