config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  get '/info', to: 'static_pages#info'
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/impersonation-book/sitemaps/sitemap.xml.gz")
  get 'search_tag', to: 'targets#search_tag'

  resources :users, only: %i[new create show edit update]

  resources :targets do
    resources :results, only: %i[create]
  end

  resources :results, only: %i[index show edit update destroy] do
    resources :collaborations, only: %i[new create]
    resources :comments, only: %i[create destroy]
  end

  resources :collaborations, only: %i[destroy update show edit index] do
    resources :collaboration_comments, only: %i[create destroy]
  end
  
  resources :votes, only: %i[new create destroy index] do
    resource :likes, only: %i[create destroy]
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'ranks', to: 'ranks#index'
  get 'boards', to: 'boards#index'
  get 'collaboration_boards', to: 'collaboration_boards#index'

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy]
    resources :targets, only: %i[create new index edit update show destroy]
    resources :tags, only: %i[create new index edit update destroy]
    resources :results, only: %i[index]
    resources :collaborations, only: %i[index]
  end

end

app/models/target.rb
class Target < ApplicationRecord
  mount_uploader :target_voice, TargetVoiceUploader
  validates :name, presence: true

  has_many :results, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships

  def api_destroy(target)
    destroy_url = "/speaker/identification/v2.0/text-independent/profiles/#{target.profile_id}"
    destroy_connection = Faraday.new(url: 'https://westus.api.cognitive.microsoft.com') do |f|
      f.request :multipart
      f.request :json
      f.response :logger
      f.adapter Faraday.default_adapter
    end

    destroy_response = destroy_connection.delete do |destroy_req|
      destroy_req.url destroy_url
      destroy_req.headers = {
        'Ocp-Apim-Subscription-Key': Rails.application.credentials[:apiKey]
      }
    end
  end


  def get_profile(target)
    create_connection = Faraday.new(url: 'https://westus.api.cognitive.microsoft.com') do |f|
      f.request :multipart
      f.request :json
      f.response :logger
      f.adapter Faraday.default_adapter
    end

    create_response = create_connection.post do |create_req|
      create_req.url '/speaker/identification/v2.0/text-independent/profiles'
      create_req.headers = {
        'Ocp-Apim-Subscription-Key': Rails.application.credentials[:apiKey],
        'Content-Type': 'application/json'
      }
      create_req.body = {
        locale: "en-us"
      }
    end
    hash = JSON.parse(create_response.body)
    target.profile_id = hash["profileId"]
  end


  def enrollment_voice(target)
    if Rails.env.production?
      voice = URI.open(target.target_voice.url) # 本番環境のみ
    else
      voice = "/Users/beppumasaki/workspace/my_app/impersonation_practice/public" + URI.decode_www_form_component("#{target.target_voice.url}") # 本番環境以外
    end

    enrollments_url = "/speaker/identification/v2.0/text-independent/profiles/#{target.profile_id}/enrollments"
    
    enrollments_connection = Faraday.new(url: 'https://westus.api.cognitive.microsoft.com') do |f|
      f.request :multipart
      f.request :url_encoded
      f.response :logger
      f.adapter Faraday.default_adapter
    end

    enrollments_response = enrollments_connection.post do |enrollments_req|
      enrollments_req.url enrollments_url 
      enrollments_req.headers = {
      'Ocp-Apim-Subscription-Key': Rails.application.credentials[:apiKey],
      'Content-Type': 'audio/wav',
      'Transfer-Encoding': 'chunked'
      }
      enrollments_req.body = Faraday::Multipart::FilePart.new(voice, 'audio/wav')
    end
  end

end

app/controllers/admin/targets_controller.rb
class Admin::TargetsController < Admin::BaseController
  before_action :set_target, only: %i[show edit update destroy]

      def show
        @tag_relationships = @target.tags
        @tag_list = @target.tags.pluck(:name).join(',')
      end
    
      def index
        @targets = Target.order(created_at: :desc)
        @tag_list = Tag.all
      end
    
      def new
        @target = Target.new
        @tag_list = @target.tags.pluck(:name).join(',')
      end
    
      def edit
        @tag_list = @target.tags.pluck(:name).join(',')
      end
    
      def update
        if @target.update(target_params)
          redirect_to admin_target_path(@target)
        else
          render :edit
        end
      end
    
      def destroy
        @target.api_destroy(@target)
        @target.destroy
        redirect_to admin_targets_path
      end
    
      def create
        @target = Target.new(target_params)
        #profile作成
        @target.get_profile(@target)

        if @target.save
          #音声をAPIのprofileに登録
          @target.enrollment_voice(@target)
          redirect_to admin_targets_path
        else
          render :new
        end
      end
    
      private

      def set_target
        @target = Target.find(params[:id])
      end
    
      def target_params
        params.require(:target).permit(:name, :target_voice, tag_ids: [])
      end

end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  skip_before_action :require_login, only: [:show, :index, :search_tag]
  
  def show
    @target = Target.find(params[:id])
  end

  def index
    @targets = Target.all
    @tag_list=Tag.all
  end

  def search_tag
    #検索結果画面でもタグ一覧表示
    @tag_list = Tag.all
    #検索されたタグを受け取る
    @tag = Tag.find(params[:tag_id])
    #検索されたタグに紐づく投稿を表示
    @targets = @tag.targets
  end

end

app/views/targets/_target.html.erb
<div class="card shadow mx-auto my-2 justify-content-center" style="width: 20rem;">
    <div class="card-body">
      <%= link_to target_path(target), class: 'card-text text-muted' do %>
        <h3><%= target.name %></h3>
      <% end %>
    </div>
</div>

app/views/targets/index.html.erb
<% set_meta_tags title: t('.title') %>
<div class="container text-muted mt-3">
  <div class="center-block">
    <%= image_tag 'maneo_choice.png', class:'logo mx-auto d-block', size: '100x50' %>
    <h1 class="text-center mt-1">モノマネするお題を選択してください</h1>
  </div>
  <div class="targets-wrapper">
    <div class="top-cards pt-5 pb-4">
      <!-- ターゲット一覧 -->
        <div class="row justify-content-center">
          <% if @targets.present? %>
            <%= render partial: 'target', collection: @targets %>
          <% else %>
            <p>お題の登録はありません。</p>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/targets/search_tag.html.erb
<% set_meta_tags title: t('.title') %>
<div class="container text-muted mt-3">
  <div class="center-block">
    <%= image_tag 'maneo_choice.png', class:'logo mx-auto d-block', size: '100x50' %>
    <h1 class="text-center mt-1">モノマネするお題を選択してください</h1>
  </div>

    <!--タグリスト-->
    <h5 class="tag-list mt-4">
      <i class="fas fa-tag mb-2"> タグからお題を探す</i><br>
      <%=link_to "全て(#{Target.all.count})", targets_path, class: 'badge badge-primary' %>
        <% @tag_list.each do |list|%>
            <%=link_to "#{list.name}(#{list.targets.count})", search_tag_path(tag_id: list.id), class: 'badge badge-primary' %>
        <% end %>
    </h5>

  <div class="targets-wrapper">
    <div class="top-cards pt-5 pb-4">
      <!-- ターゲット一覧 -->
        <div class="row justify-content-center">
          <% if @targets.present? %>
            <%= render partial: 'target', collection: @targets %>
          <% else %>
            <p>お題の登録はありません。</p>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/targets/show.html.erb
<% set_meta_tags title: t('.title') %>
<div class="container text-muted">
  <div class='top-wrapper'>
    <div class='top-inner-text text-center', id='button'>
      <div>
        <h1 class="text-center mt-5"><%= @target.name %></h1>
      </div>
      <div>
        <p class = "mt-3" id="notice" >録音ボタンを押して全力でモノマネしよう！</p>
      </div>

      <div class="mt-4 mb-5">
        <button class = "btn btn-primary btn-lg" id="rec" >録音する</button>
        <button class = "btn btn-danger btn-lg d-none" id="result">採点する</button>
            <%= form_with url:target_results_path(@target), id: "voiceform", local: true do |f| %>
              <%= f.hidden_field :target_id, :value => @target.id %>
              <%= f.hidden_field :impersonation_voice  %>
              <%= f.hidden_field :score, :value => 0  %>
            <% end %>
      </div>
      <section class="tape">
        <div class="sound-clips my-2">
          <audio id="play" controls></audio>
          <a id ="download" href="#" type="hidden"></a>
          <a id="stop" type="hidden"></a>
        </div>
        <div class="row justify-content-center pt-2">
            <button class = "col-2 btn btn-primary mr-3 invisible" id="playid" >再生する</button>
            <%= link_to "やり直す", request.path_info, id: "restart", class: "col-2 btn btn-primary ms-3 invisible" %>
        </div>
        <%= image_tag 'maneo_sing.png', class:'target-logo mx-auto d-block', size: '1200x300' %>
      </section>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'app', 'data-turbolinks-track': 'reload' %>