config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  get '/info', to: 'static_pages#info'
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/impersonation-book/sitemaps/sitemap.xml.gz")
  get 'search_tag', to: 'targets#search_tag'

  resources :users, only: %i[new create show edit update]

  resources :targets do
    resources :results, only: %i[create]
  end

  resources :results, only: %i[index show edit update destroy] do
    resources :collaborations, only: %i[new create]
    resources :comments, only: %i[create destroy]
  end

  resources :collaborations, only: %i[destroy update show edit index] do
    resources :collaboration_comments, only: %i[create destroy]
  end
  
  resources :votes, only: %i[new create destroy index] do
    resource :likes, only: %i[create destroy]
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'ranks', to: 'ranks#index'
  get 'boards', to: 'boards#index'
  get 'collaboration_boards', to: 'collaboration_boards#index'

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy]
    resources :targets, only: %i[create new index edit update show destroy]
    resources :tags, only: %i[create new index edit update destroy]
    resources :results, only: %i[index]
    resources :collaborations, only: %i[index]
  end

end

app/views/shared/_after_login_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <%= image_tag 'maneo_face.png', class:'header-logo navbar-brand', size: '50x50' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "モノマネする", targets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "お題総選挙", votes_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            みんなのモノマネ
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "公開中のモノマネ", boards_path, class: "dropdown-item" %></li>
            <li><%= link_to "公開中のコラボ", collaboration_boards_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "ランキング", ranks_path, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle btn btn-primary" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user mr-2"></i><%= "#{current_user.name}さん" %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "プロフィール", user_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "ログアウト", logout_path, method: :delete, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer'>
  <div class="text-white">
      <ul class="row justify-content-center pr-5">
        <div class="col-auto p-3">
          <%= link_to '利用規約', '/terms', class: "text-white"%>
        </div>
        <div class="col-auto p-3">
          <%= link_to 'プライバシーポリシー', '/privacy', class: "text-white" %>
        </div>
        <div class="col-auto p-3">
          <%= link_to 'お問い合わせ', '/info', class: "text-white" %>
        </div>
        <div class="col-auto p-3">
          |
        </div>
        <div class="col-auto pt-3">
           ©︎2022 ものまねお
        </div>
      </ul>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
      <%= link_to root_path do %>
        <%= image_tag 'maneo_face.png', class:'header-logo navbar-brand', size: '50x50' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "モノマネする", targets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "公開中のモノマネ", boards_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto mb-lg-0">
        <li class="nav-item">
          <%= link_to "新規登録", new_user_path, class: "nav-link btn btn-primary mt-1 mr-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", login_path, class: "nav-link btn btn-primary mt-1" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>