config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  get '/info', to: 'static_pages#info'
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/impersonation-book/sitemaps/sitemap.xml.gz")
  get 'search_tag', to: 'targets#search_tag'

  resources :users, only: %i[new create show edit update]

  resources :targets do
    resources :results, only: %i[create]
  end

  resources :results, only: %i[index show edit update destroy] do
    resources :collaborations, only: %i[new create]
    resources :comments, only: %i[create destroy]
  end

  resources :collaborations, only: %i[destroy update show edit index] do
    resources :collaboration_comments, only: %i[create destroy]
  end
  
  resources :votes, only: %i[new create destroy index] do
    resource :likes, only: %i[create destroy]
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'ranks', to: 'ranks#index'
  get 'boards', to: 'boards#index'
  get 'collaboration_boards', to: 'collaboration_boards#index'

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy]
    resources :targets, only: %i[create new index edit update show destroy]
    resources :tags, only: %i[create new index edit update destroy]
    resources :results, only: %i[index]
    resources :collaborations, only: %i[index]
  end

end

app/models/result.rb
class Result < ApplicationRecord
   mount_uploader :impersonation_voice, ImpersonationVoiceUploader
   belongs_to :target
   belongs_to :user
   has_many :comments, dependent: :destroy
   has_many :collaborations, dependent: :destroy
   after_create :analyze

   enum state: { not_published: 0, published: 1 }

    def analyze
      result = self
      target = self.target

      #APIに投げるprofile_idを5つ選ぶ。まずはtargetを除く4つのお題を抽出
      sample_profiles = Target.where.not(profile_id: target.profile_id).sample(4)
      sample_profile_ids = (0..3).map do |num|
        sample_profiles[num].profile_id
      end
      profile_ids = sample_profile_ids << target.profile_id
      profile_ids_params = profile_ids.join(',')

      result.compare(profile_ids_params, target, result)
    end

    def compare(ids, target, result)
      if Rails.env.production?
        voice = URI.open(result.impersonation_voice.url) # 本番環境のみ
      else
        voice = "/Users/beppumasaki/workspace/my_app/impersonation_practice/public" + URI.decode_www_form_component("#{result.impersonation_voice.url}") # 本番環境以外
      end 

      connection = Faraday.new(url: 'https://westus.api.cognitive.microsoft.com') do |f|
        f.request :multipart
        f.request :url_encoded
        f.response :logger
        f.adapter Faraday.default_adapter
      end
  
      #APIにprofile_ids_paramsを指定
      response = connection.post do |req|
        req.url '/speaker/identification/v2.0/text-independent/profiles/identifySingleSpeaker'
        req.headers = {
          'Ocp-Apim-Subscription-Key': Rails.application.credentials[:apiKey],
          'Content-Type': 'audio/wav',
          'Transfer-Encoding': 'chunked'
        }
        req.body = Faraday::Multipart::FilePart.new(voice, 'audio/wav')
        req.params = {
          profileIds: ids
        }
      end
      result.judge(response, target, result)
    end

    def judge(response, target, result)
      hash = JSON.parse(response.body)
      
      #profile_idのみ配列で取得
      profile_id_list = (0..4).map do |num|
        hash["profilesRanking"][num]["profileId"]
      end
      
      #targetのprofile_idと同一のものを抽出
      same_profile_id = profile_id_list.select do |x|
        x == target.profile_id
      end

      #お題のレスポンスが返ってきているprofile_idは何番目か
      same_profile_id_number = profile_id_list.index(same_profile_id*"")

      result.score = hash["profilesRanking"][same_profile_id_number]["score"]*140
      result.score = 0 if result.score < 0
      result.match_target = Target.find_by(profile_id: hash["profilesRanking"][0]["profileId"]).name
      result.save
    end
end

app/controllers/admin/results_controller.rb
class Admin::ResultsController < Admin::BaseController
  def index
    @results = Result.order(created_at: :desc)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  skip_before_action :require_login, only: %i[show create]
  before_action :set_result, only: %i[show edit update destroy]
  before_action :user_check, only: %i[edit update destroy]
  before_action :set_target, only: %i[show edit]

  def show
    @user = @result.user
    @comments = @result.comments
    @comment = Comment.new
  end

  def index
    @results = current_user.results
  end

  def edit; end

  def destroy
    @result.destroy
    redirect_to results_path
  end

  def update
    @result.update(update_result_params)
    redirect_to results_path
  end
  
  def create
    @result = Result.new(result_params)
    @result.user_id = current_user.id if current_user
    @result.save

    render json: { url: result_url(@result) }
  end

  private

  def set_result
    @result = Result.find(params[:id])
  end

  def set_target
    @target = Target.find(@result.target_id)
  end

  def result_params
    params.permit(:target_id, :impersonation_voice, :score, :user_id)
  end

  def update_result_params
    params.require(:result).permit(:body, :state)
  end

  def user_check
    @user = @result.user
    redirect_to root_path if current_user != @user
  end

end

app/views/results/_result.html.erb
<tr>
  <td class='align-middle'><%= l result.created_at, format: :short %></td>
  <td class='align-middle td-pe-none'><%= result.score %>点</td>
  <td class='align-middle'><%= Target.find(result.target_id).name %></td>
  <td class='align-middle td-pe-none'><%= result.state_i18n %></td>
  <td class='align-middle'>
    <%= link_to t('defaults.show'), result_path(result), class: 'btn btn-info mr-3' %>
    <%= link_to result_path(result), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger' do %>
      <i class="far fa-trash-alt"></i> 
    <% end %>
  </td>
</tr>

app/views/results/edit.html.erb
<% set_meta_tags title: t('.title') %>
<div class="container mt-5 text-muted">
  <div class='top-wrapper'>
    <div class='top-inner-text text-center'>
    <h1><i class="fa-solid fa-microphone mr-2 mb-4"></i><%= t('.title') %></h1>
      <div class='score'>
        <h2><%= @target.name %> : <%= @result.score %>点</h2>
      </div>
      <div class='advice'>
        <h2>
          <% if @result.match_target != @target.name then %>
          　おすすめのモノマネ：<%= @result.match_target%>
          <% end %>
        </h2>
      </div>
      <%=audio_tag("#{@result.impersonation_voice.url}", controls: true) %>
    </div> 
  
    <div class="row">
        <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
          <%= form_with model: @result, url: result_path(@result), local: true do |f| %>
              <div class="form-group">
                <%= f.label :body %>
                <%= f.text_field :body, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :state %>
                <%= f.select :state, Result.states_i18n.invert, {}, class: 'form-control' %>
              </div>
              <%= f.submit t('defaults.update'), class: 'btn btn-primary' %>
          <% end %>
        </div>
    </div>
  </div>
</div> 

app/views/results/index.html.erb
<% set_meta_tags title: t('.title') %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <h1 class="text-muted mt-5 mb-3">
        <i class="fa-solid fa-microphone mr-2"></i>
        <%= t('.title') %>
        <%= link_to t('collaborations.index.title'), collaborations_path, class:"btn btn-primary mr-3 mb-2 float-right" %>
      </h1>
      <table class="table table-striped">
        <thead class="thead-primary">
        <tr>
          <th scope="col"><%= Result.human_attribute_name(:created_at) %></th>
          <th scope="col"><%= Result.human_attribute_name(:score) %></th>
          <th scope="col"><%= Target.human_attribute_name(:name) %></th>
          <th scope="col"><%= Result.human_attribute_name(:state) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
          <%= render @results %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/results/show.html.erb
<% set_meta_tags title: t('.title') %>
<div class="container pt-5 text-muted">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><i class="fa-solid fa-microphone mr-2"></i><%= t('.title') %></h1>
      <article class="card">
        <div class="card-body">
          <% unless current_user.nil? %>
            <%= link_to "コラボする", new_result_collaboration_path(@result), class: 'float-right btn btn-info' %>
            <% if @result.user_id == current_user.id %>
              <%= link_to edit_result_path(@result), class: 'btn btn-primary float-right mr-2' do %>
                <i class="fa-regular fa-pen-to-square"></i>
              <% end %>
            <% end %>
          <% end %>  
          <div class='row text-center'>
            <div class='col-md-9'>
              <h1 style='display: inline;'><%= @target.name %>：<%= @result.score %>点</h1>
              <div class='advice mb-5'>
                <p>
                  <% if @result.match_target == @target.name then %>
                   <%= @target.name %>はあなたにぴったりですね！
                  <% else %>
                   この声は、<%= @result.match_target%>もおすすめです！
                  <% end %>
                </p>
              </div>
              <%= audio_tag("#{@result.impersonation_voice.url}", controls: true) %>
              <% if logged_in? %>
              <ul class="list-inline">
                <li class="list-inline-item">by <%= @user.name %></li>
                <li class="list-inline-item"><%= l @result.created_at, format: :short %></li>
              </ul>
              <% end %>
            </div>
          </div>
          <p><%= simple_format(@result.body) %></p>
        </div>
      </article>
        <%= link_to "https://twitter.com/share?url=#{request.url}&hashtags=ものまねお,モノマネ採点&text=【#{@target.name}】に挑戦しました！%0a%0a結果は… #{@result.score}点/100点でした！%0aコラボ待ってます！%0a%0a", class: 'btn btn-primary float-right', target: '_blank' do %>
          <i class="fab fa-twitter pe-1"></i><%= t('.share_to_twitter') %>
        <% end %>          
    </div>
  </div>

<!-- コメントエリア -->
  <%= render 'comments/comments', { comments: @comments } if Comment.where(result_id: @result.id).count > 0 %> 
<!-- コメントフォーム -->
  <%= render 'comments/form', { result: @result, comment: @comment } if logged_in? %>
  <h4 class= "text-center py-3" ><%= link_to 'お題を選ぶ', targets_path, class: "link" %></h4>
</div>